spring.application.name=02-Spring-jdbc-select-operations

# Data Source properties
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/sbai02
spring.datasource.username=root
spring.datasource.password=root

#   jdbc:      --> the standard java protocol prefix required for all jdbc connection strings.
#   postgresql --> specifies the target database type
#   localhost  --> means the db server is on your own local computer(same machine running the code)
#   5432       --> the default network port number used my PostgreSql
#   sbai02     --> the specific name of the database you want to open and use



